Profiles:

    ARTXCHGOrdererGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
        Consortiums:
            ARTXCHG:
                Organizations:
                    - *Org1
                    - *Org2
                    - *ArtMarket

    Org1Channel:
        Consortium: ARTXCHG
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Org1
                - *ArtMarket
    Org2Channel:
        Consortium: ARTXCHG
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Org2
                - *ArtMarket

Organizations:

    - &OrdererOrg
        Name: OrdererMSP
        ID: OrdererMSP

        MSPDir: crypto-config/ordererOrganizations/artxchg.com/msp

    - &Org1
        Name: Org1MSP
        ID: Org1MSP

        MSPDir: crypto-config/peerOrganizations/org1.artxchg.com/msp

        AnchorPeers:
            - Host: peer0.org1.artxchg.com
              Port: 7051
            - Host: peer1.org1.artxchg.com
              Port: 7051

    - &Org2
        Name: Org2MSP
        ID: Org2MSP

        MSPDir: crypto-config/peerOrganizations/org2.artxchg.com/msp

        AnchorPeers:
            - Host: peer0.org2.artxchg.com
              Port: 7051
            - Host: peer1.org2.artxchg.com
              Port: 7051

    - &ArtMarket
        Name: ArtMarketMSP
        ID: ArtMarketMSP

        MSPDir: crypto-config/peerOrganizations/market.artxchg.com/msp

        AnchorPeers:
            - Host: peer0.market.artxchg.com
              Port: 7051

Orderer: &OrdererDefaults
    OrdererType: solo

    Addresses:
        - orderer.artxchg.com:7050

    BatchTimeout: 2s

    BatchSize:

        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB

    Organizations:


Application: &ApplicationDefaults
    Organizations:

