OrdererOrgs:
  - Name: Orderer
    Domain: artxchg2.com
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Org1
    Domain: org1.artxchg2.com
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: Org2
    Domain: org2.artxchg2.com
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: Org3
    Domain: org3.artxchg2.com
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: ArtMarket
    Domain: market.artxchg2.com
    Template:
      Count: 1
    Users:
      Count: 1

